# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
a = np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [12]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [13]:
b.shape

(40,)

5. Print the type of the previous array in question 3

In [17]:
b.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [20]:
print(np.__version__)

1.18.1


7. Print the dimension of the array in question 3


In [19]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sajid/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Sajid/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sajid/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

8. Create a boolean array with all the True values

In [9]:
l = np.array([1,2,3])
m = np.array([4,5,6])
l<m

array([ True,  True,  True])

9. Create a two dimensional array




In [45]:
d = np.arange(0,9)
d.resize((2,5))
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 0]])

10. Create a three dimensional array



In [48]:
e = np.arange(1,9)
e.resize(3,3)
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
import numpy as np
f = np.arange(1,10)



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

12. Create a null vector of size 10 but the fifth value which is 1 

In [16]:
g = np.zeros((10))
g[4]=1
g

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [19]:
h = np.ones(9).reshape(3,3)
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [33]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = arr.astype(float)
arr2.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [35]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [41]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3[arr1>arr2]
arr3

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [47]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [49]:
arr = np.arange(10)
arr[arr % 2 == 1]= -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [52]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [60]:
i = np.ones((5,5))
i[1:-1, 1:-1]= 0
i

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [65]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]= 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]= 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [88]:
arr5 = np.arange(0,10)
arr5.resize(2,5)
arr5[0,::]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [89]:
arr5 = np.arange(0,10)
arr5.resize(2,5)
arr5[1,::]

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [91]:
arr5 = np.arange(0,10)
arr5.resize(2,5)
arr5[0:2,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [98]:
arr6= np.random.randn(10,10)
arr6.max(), arr6.min()

(2.297354141065742, -2.6420216950950453)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [99]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [103]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.intersect1d(a, b))


(array([0, 1], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [110]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[np.where(names!= 'Will')]

array([[ 0.26532395,  2.08396644, -0.4670483 ,  1.61063348],
       [ 1.02593758, -0.39431384, -0.15024317, -1.36545483],
       [ 0.48201244,  0.45083608, -0.3513607 ,  1.33623764],
       [ 1.32062815, -0.14121509,  0.12122128, -0.26717015],
       [ 1.38903623,  1.65420269, -0.21979475,  0.12861674]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [32]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[np.where(names == 'Bob')]

array([[-1.86045353, -1.81338909, -1.02356436,  0.03300966],
       [ 0.23374826,  0.96962959,  0.66800791, -1.25931822]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [217]:
x = np.array([0.33,1.23,2.433,3.2,4.2,5.6,6.8,7.2,8.1,9.1, 10.5, 11.3, 12.21, 13.0 ,14.1])
x.reshape((5,3))

array([[ 0.33 ,  1.23 ,  2.433],
       [ 3.2  ,  4.2  ,  5.6  ],
       [ 6.8  ,  7.2  ,  8.1  ],
       [ 9.1  , 10.5  , 11.3  ],
       [12.21 , 13.   , 14.1  ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [229]:
x = np.array([0.33,1.23,2.433,3.2,4.2,5.6,6.8,7.2,8.1,9.1, 10.5, 11.3, 12.21, 13.0 ,14.1])
x.resize(2,2,4)
x

array([[[ 0.33 ,  1.23 ,  2.433,  3.2  ],
        [ 4.2  ,  5.6  ,  6.8  ,  7.2  ]],

       [[ 8.1  ,  9.1  , 10.5  , 11.3  ],
        [12.21 , 13.   , 14.1  ,  0.   ]]])

33. Swap axes of the array you created in Question 32

In [228]:
x = np.array([0.33,1.23,2.433,3.2,4.2,5.6,6.8,7.2,8.1,9.1, 10.5, 11.3, 12.21, 13.0 ,14.1])
x.resize(2,2,4)
np.swapaxes(x, 2, 0)

array([[[ 0.33 ,  8.1  ],
        [ 4.2  , 12.21 ]],

       [[ 1.23 ,  9.1  ],
        [ 5.6  , 13.   ]],

       [[ 2.433, 10.5  ],
        [ 6.8  , 14.1  ]],

       [[ 3.2  , 11.3  ],
        [ 7.2  ,  0.   ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [280]:
y = np.arange(10)
x = np.sqrt(y)
x[x < 0.5]=0
x

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [290]:
a = np.random.randn(12)
b = np.random.randn(12)
c = np.maximum(a,b)
c

array([-0.07023389,  0.81520671,  2.20312958,  0.23509213,  0.20715268,
        0.60360793, -0.33178265,  2.67431052,  0.97848691, -0.2092818 ,
       -0.44824114,  1.04976648])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [310]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.sort(names)
np.unique(a)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [319]:
a = np.array([1,2,3,4,5]) 

b = np.array([5,6,7,8,9])

a = np.setdiff1d(a,b)

a


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:
import numpy as np
sampleArray = np.array([[34,43,73], [82,22,12], [53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis= 0)
np.insert(sampleArray, 1, newColumn, axis= 0)

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [68]:
a = np.random.randn(20,20)
b= np.matrix.cumsum(a)
b


array([  0.29226111,   0.8717148 ,   2.51106351,   1.81896597,
         0.92552337,   1.53869399,   1.81967885,   0.43868464,
         1.08154776,   1.3563782 ,   3.41333235,   2.81046495,
         0.95709528,   1.14310594,  -0.48692889,  -2.13884699,
        -1.04861076,  -0.8429017 ,  -0.96983883,  -0.41096423,
         0.89233915,   3.24107802,   3.43121454,   3.44562454,
         1.86906276,   0.49525757,  -0.14626332,  -1.0905888 ,
         0.3976647 ,   0.48556131,  -0.46849375,  -1.16003417,
        -2.08845005,  -3.24840791,  -2.84637248,  -2.72194774,
        -3.77436994,  -4.9977395 ,  -6.05920083,  -5.80926877,
        -5.23997081,  -7.06965659,  -8.15580892,  -9.41947439,
        -9.32216864,  -9.13492492,  -8.1242604 ,  -7.35455156,
        -6.06556154,  -6.15812588,  -4.51615779,  -2.89735356,
        -3.16263645,  -3.33747625,  -3.46609174,  -2.84702095,
        -4.84296098,  -4.37017125,  -4.38199307,  -5.09513321,
        -5.45713681,  -5.63182532,  -4.04731946,  -3.38